// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3ZNJi-WewDKmi6m6-pZKCIVNKsPC_eQ',
    appId: '1:371214127756:android:1ab8f0af3f604e0b60a1a9',
    messagingSenderId: '371214127756',
    projectId: 'kilochat-realm',
    storageBucket: 'kilochat-realm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ0UFt4Nrz2OnBQvI3qio72Abw76bcRG4',
    appId: '1:371214127756:ios:ba86b9e1d8b4750860a1a9',
    messagingSenderId: '371214127756',
    projectId: 'kilochat-realm',
    storageBucket: 'kilochat-realm.appspot.com',
    iosClientId: '371214127756-7hg0fj2a2u8jbo8ur7veael6vfoboan7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kilochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ0UFt4Nrz2OnBQvI3qio72Abw76bcRG4',
    appId: '1:371214127756:ios:672fefd8423f42c560a1a9',
    messagingSenderId: '371214127756',
    projectId: 'kilochat-realm',
    storageBucket: 'kilochat-realm.appspot.com',
    iosClientId: '371214127756-qpak0482c07firum3oukirg1kajoe5d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kilochat.RunnerTests',
  );
}
