name: bundled_realm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.0.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  analyzer: ^5.2.0
  realm: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - realm/initial.realm
  

