name: myapp
description: A simple command-line application using Realm Dart SDK.
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  realm_dart: 

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^2.1.2
