name: CI new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Use this to provide a version of realm for updating the samples.
        required: true
        type: string

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update realm_dart in pubspec.yaml
        uses: jacobtomlinson/gha-find-replace@b76729678e8d52dadb12e0e16454a93e301a919d #! 2.0.0
        with:
          find: 'realm_dart: .*'
          replace: 'realm_dart: ${{ inputs.version }}'
          include: '**pubspec.yaml'

      - name: Update realm in pubspec.yaml
        uses: jacobtomlinson/gha-find-replace@b76729678e8d52dadb12e0e16454a93e301a919d #! 2.0.0
        with:
          find: 'realm: .*'
          replace: 'realm: ${{ inputs.version }}'
          include: '**pubspec.yaml'

      - name: Create Version Upgrade PR
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad #! 3.10.1
        with:
          branch: release/${{ inputs.version }}
          base: master
          title: '[Realm version upgrade ${{ inputs.version }}]'
          draft: false
          body: An automated PR for released realm version.
          commit-message: Update samples with realm ${{ inputs.version }}
          token: ${{ secrets.REALM_CI_PAT }}
